const express = require('express');
const router = express.Router();
const AutomationFlowController = require('../Controller/AutomationFlowController');
const AutomationTriggerController = require('../Controller/AutomationTriggerController');
const AutomationActionController = require('../Controller/AutomationActionController');
const AutomationController = require('../Controller/AutomationController');
// FLOW
router.post('/flows', AutomationFlowController.create);
router.get('/flows', AutomationFlowController.getAllflow);
router.patch('/flows/:flow_id', AutomationFlowController.update);
router.delete('/flows/:flow_id', AutomationFlowController.remove);
router.post('/flows/:flow_id/enable', AutomationFlowController.enable);
router.post('/flows/:flow_id/disable', AutomationFlowController.disable);
router.get('/flows/:flow_id', AutomationFlowController.getFlow);
router.post('/flows/:flow_id/validate', AutomationFlowController.validate);
router.get('/flows/:flow_id/editor', AutomationFlowController.getEditor);
router.put('/flows/:flow_id/editor', AutomationFlowController.saveEditor);
router.post('/flows/:flow_id/active', AutomationFlowController.active);
router.post('/flows/:flow_id/publish', AutomationFlowController.publish);
module.exports = router;
