const express = require('express');
const router = express.Router();
const LeadController = require('../Controller/LeadController');

const multer = require('multer');
const upload = multer({ dest: 'uploads/' });
router.post('/import', upload.single('file'), LeadController.importLeads);
router.post('/interest', LeadController.trackInterest);
router.post('/from-interest', LeadController.fromInterest);
router.get('/qualified', LeadController.getQualifiedLeads);
router.get('/pipeline/metrics', LeadController.getPipelineMetrics);
router.get('/pipeline/summary', LeadController.getPipelineSummary);
router.get('/pipeline/columns', LeadController.getPipelineColumns);
router.patch('/pipeline/:leadId/status', LeadController.updateLeadStatus);
router.get('/detail/:id', LeadController.getLeadDetails);
router.post('/', LeadController.create);
router.get('/', LeadController.getAll);
router.get('/:id', LeadController.getById);
router.patch('/:id', LeadController.update);
router.patch('/:id/status', LeadController.changeStatus);
router.get('/:id/status-history', LeadController.listStatusHistory);
router.post('/:id/interactions', LeadController.addInteraction);
router.get('/:id/interactions', LeadController.listInteractions);
router.post('/:id/convert', LeadController.convert);
router.post('/:id/auto-convert', LeadController.autoConvert);
router.post('/:leadId/rescore', LeadController.rescoreLead);
router.post('/rescore/daily', LeadController.rescoreDaily);
router.get('/:leadId/predictions', LeadController.getPredictions);
router.post('/:id/tags', LeadController.addTag);           
router.delete('/:id/tags/:tag', LeadController.removeTag); 
router.get('/tags/:tag', LeadController.findLeadsByTag);  
module.exports = router;
